### PR TITLE
Build wheels for Windows

### PR DESCRIPTION
**Pull request by McSinyx**
Has something to do with the Cython warning:

    src\palace.cpp(1026): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(1027): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(4770): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(4771): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(4778): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(4785): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(5140): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(5141): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(5148): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(5155): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(12167): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(12168): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(12176): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(12183): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(12950): error C3431: 'DistanceModel': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(15590): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(15682): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(21083): error C3431: 'Spatialize': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(21086): error C3431: 'Spatialize': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(29480): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(29481): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(29485): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(29520): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(29534): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(29535): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(29539): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(29574): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration

### CODE REVIEW

**Comment by McSinyx** [comment]
Has something to do with the Cython warning:

    src\palace.cpp(1026): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(1027): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(4770): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(4771): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(4778): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(4785): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(5140): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(5141): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(5148): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(5155): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(12167): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(12168): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(12176): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(12183): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(12950): error C3431: 'DistanceModel': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(15590): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(15682): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(21083): error C3431: 'Spatialize': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(21086): error C3431: 'Spatialize': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(29480): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(29481): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(29485): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(29520): error C3431: 'ChannelConfig': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(29534): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(29535): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(29539): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration
    src\palace.cpp(29574): error C3431: 'SampleType': a scoped enumeration cannot be redeclared as an unscoped enumeration

**Comment by McSinyx** [comment]
Closing in favor of GH-72, also because I don't think I can fix MSVC compatibility any time soon :disappointed:

**Comment by Huy-Ngo** [comment]
Hmm does it have to be MSVC? Can we use mingw-gcc instead?

**Comment by McSinyx** [comment]
Unfortunately, [the compiler used for CPython and that for the extension must match](https://github.com/cython/cython/wiki/CythonExtensionsOnWindows#less-useful-information), so we'll have to use MSVC.

**Pull request closed without merging**
