### PR TITLE
PEP 257 NO compliance

### LINKED ISSUE #94: PEP 257 compliance
We should go though the docstrings and make sure that they all comply with [PEP 257](https://www.python.org/dev/peps/pep-0257/).  The main issues at the moment I think are

* Some docstrings have the first paragraph longer than one line.
* The docstring needs to be offset from the first method by a blank line

### PR DESCRIPTION
**Pull request by 9a24f0**
Opened PR for reviews

### CODE REVIEW

**Comment by McSinyx** [comment]
Failure is irrelevant, however I'd be happy if you can make the updated flake8 happy (in a separate commit please).

**Comment by 9a24f0** [comment]
> Failure is irrelevant, however I'd be happy if you can make the updated flake8 happy (in a separate commit please).

wait, is that you mean seperate commit on master? o.O

**Comment by McSinyx** [comment]
> wait, is that you mean seperate commit on master? o.O

Either way is cool to me.  f07ea1340fff2caa9ae774f6a4694cd8c5597f14 and 639f7c9c2f480fbd4021ab6aec339d7178668533 should be squashed together though.

**Comment by McSinyx** [comment]
LOL I told you to separate commit logically so that you can rebase them onto master, but fine :smile:

**Pull request merged**
