### PR TITLE
Start writing tutorial for source manipulation

### PR DESCRIPTION
**Pull request by Huy-Ngo**

### CODE REVIEW

**Comment by McSinyx** [comment]
Note that it might be a good idea to remove the `html` and `doctrees` directories before `make html` if one changes the source structure (i.e. add/remove or move ReST files around).

**Comment by McSinyx** [comment]
To @9a24f0 too, please have a look at [Python documentation style guide](https://devguide.python.org/documenting/#style-guide), which contains many IMHO nice advises for documentation writing in general.

**Comment by Huy-Ngo** [comment]
Hmm too much conflicts... I resolve this by not resolving

**Comment by McSinyx** [comment]
LOL you can checkout doctrees and html from gh-pages but copy-pasting is indeed never a bad option.

**Pull request closed without merging**
