### PR TITLE
Set up GitHub Action for linting

### PR DESCRIPTION
**Pull request by McSinyx**
This will give faster linting feedback since we can skip compilation.

### CODE REVIEW

**Comment by Huy-Ngo** [comment]
Don't we have to install scipy for the testing?

**Comment by McSinyx** [comment]
We do (see tox.ini line 9), not for linting though.

**Review by Huy-Ngo — APPROVED** [review]
OK, I see, lgtm

**Comment by McSinyx** [comment]
Thanks!

**Pull request merged**
