### PR TITLE
Merging `new-eff` to `master` and finished relevant methods

### LINKED ISSUE #24: Implement Effect and relevant methods
Since this method uses unimplemented class `Effect`, I will leave this until @9a24f0 finish it.

### PR DESCRIPTION
**Pull request by 9a24f0**

### CODE REVIEW

**Comment by McSinyx** [comment]
It's already approved, just squash 'em all with a message of

> Implement Effect and relevant methods

**Comment by McSinyx** [comment]
That's not what I mean but OK.  Run git log and you'll understand what I mean.

**Comment by McSinyx** [comment]
BTW, @9a24f0, please create a PyPI account so I can add you as a maintainer, so you also can upload source distribution there.

**Comment by McSinyx** [comment]
Gentil ping on the PyPI account thing.

**Comment by 9a24f0** [comment]
@McSinyx I created [one](https://pypi.org/user/9a24f0/)

**Pull request merged**
